# encoding: utf-8

require 'rubygems'

require 'rspec/core'
require 'rspec/core/rake_task'

task :spec do
  RSpec::Core::RakeTask.new(:spec) do |spec|
    spec.rspec_opts = ["-c","-fs"]
    spec.pattern = FileList['spec/*_spec.rb']
  end
end
